apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: minio
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-minio-internal
  namespace: minio
spec:
  issuerRef:
    name: selfsigning-issuer
    group: cert-manager.io
    kind: Issuer
  commonName: "*.minio.svc.cluster.local"
  secretName: tls-minio
  dnsNames:
    # Ingress domains
    - minio.cloudnative.nz
    - "*.minio.cloudnative.nz"
    - s3.cloudnative.nz
    - "*.s3.cloudnative.nz"
    # Internal domain
    - minio-hl-svc
    - minio-pool-0-0.mini-hl.minio
    - minio-hl-svc.default.svc.cluster.local
    - minio-pool-0-0.minio-hl.minio.svc.cluster.local
    - minio.minio.svc.cluster.local
    - minio.minio
    - minio.minio.svc
    - "*."
    - "*.minio.svc.cluster.local"
