apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager-pdns.yaml
  - minio-env-config.yaml
  - flux-receiver.yaml
  - coder.yaml
  - powerdns.yaml
  - authentik-env.yaml
  - longhorn-minio.yaml
